version: "3"

services:
  jupyter:
    image: "jupyter/datascience-notebook:latest"
    ports:
      - "10000:8888"
    volumes:
      - ./work:/home/jovyan/work
    container_name: jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
